networks:
  catalyst_network:
    driver: bridge

volumes:
  catalyst_count_local_postgres_data: {}
  catalyst_count_local_postgres_data_backups: {}
  catalyst_count_local_redis_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: catalyst_count_local_django
    container_name: catalyst_count_local_django
    depends_on:
      - postgres
      - redis
      - mailpit
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start
    networks:
      - catalyst_network

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: catalyst_count_production_postgres
    container_name: catalyst_count_local_postgres
    volumes:
      - catalyst_count_local_postgres_data:/var/lib/postgresql/data
      - catalyst_count_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    networks:
      - catalyst_network

  redis:
    image: docker.io/redis:6
    container_name: catalyst_count_local_redis
    
    volumes:
      - catalyst_count_local_redis_data:/data
    networks:
      - catalyst_network
  
  mailpit:
    image: docker.io/axllent/mailpit:latest
    container_name: mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - catalyst_network

  celeryworker:
    <<: *django
    image: catalyst_count_local_celeryworker
    container_name: catalyst_count_local_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker
    networks:
      - catalyst_network

  celerybeat:
    <<: *django
    image: catalyst_count_local_celerybeat
    container_name: catalyst_count_local_celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat
    networks:
      - catalyst_network

  flower:
    <<: *django
    image: catalyst_count_local_flower
    container_name: catalyst_count_local_flower
    ports:
      - '5555:5555'
    command: /start-flower
    networks:
      - catalyst_network
